[package]
name = "reth-direct-db-uniswap-storage"
version = "0.0.0"
publish = false
edition = "2021"
license = "Apache-2.0"


[dependencies]
eyre = "0.6"
lazy_static = "1.5.0"
rayon = "1.10.0"
rkyv = "0.8.8"
thiserror = "1.0"
tracing = "0.1"

reth-chainspec = { git = "https://github.com/paradigmxyz/reth", rev="d3114b4" }
reth-db = { git = "https://github.com/paradigmxyz/reth", rev="d3114b4" }
reth-primitives = { git = "https://github.com/paradigmxyz/reth", rev="d3114b4", features = ["asm-keccak"]}
reth-provider = { git = "https://github.com/paradigmxyz/reth", rev="d3114b4" }
reth-rpc = { git = "https://github.com/paradigmxyz/reth", rev="d3114b4" }
reth-rpc-types = { git = "https://github.com/paradigmxyz/reth", rev="d3114b4" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", rev="d3114b4" }
reth-node-types = { git = "https://github.com/paradigmxyz/reth", rev="d3114b4" }
reth-rpc-eth-types = { git = "https://github.com/paradigmxyz/reth", rev="d3114b4" }
reth-blockchain-tree = { git = "https://github.com/paradigmxyz/reth", rev="d3114b4" }

alloy = { version = "0.3.6", features = ["rpc-types", "asm-keccak"] }
alloy-sol-types = "0.8.3"


[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
tracing-subscriber = "0.3"

pool-sync = { git="https://github.com/Zacholme7/PoolSync", rev="29a6e5a" }
amms = { git="https://github.com/darkforestry/amms-rs", rev="a4edb40"}